/*
 * JSP generated by Resin Professional 3.1.8 (built Mon, 17 Nov 2008 02:28:01 PST)
 */

package _jsp._web_22dinf._view;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import com.mvc.entity.*;

public class _student__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((request.getContextPath() ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_loop_0 == null)
        _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
      java.lang.Object _jsp_items_1 = _caucho_expr_0.evalObject(_jsp_env);
      java.util.Iterator _jsp_iter_1 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_1);
      _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
      Object _jsp_oldVar_1 = pageContext.getAttribute("student");
      while (_jsp_iter_1.hasNext()) {
        Object _jsp_i_1 = _jsp_iter_1.next();
        pageContext.setAttribute("student", _jsp_i_1);
        _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _caucho_expr_1.print(out, _jsp_env, true);
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _caucho_expr_1.print(out, _jsp_env, true);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_2.print(out, _jsp_env, true);
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_3.print(out, _jsp_env, true);
        out.write(_jsp_string7, 0, _jsp_string7.length);
        _caucho_expr_1.print(out, _jsp_env, true);
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      pageContext.pageSetOrRemove("student", _jsp_oldVar_1);
      out.write(_jsp_string9, 0, _jsp_string9.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 3416598224022892719L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${student.id}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${student.user}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${student.psw}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/view/student.jsp"), -8449771606936697907L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("include/head.jsp"), -8732771332693712214L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;

  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string6;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  static {
    _jsp_string4 = "\r\n	<tr id=\"".toCharArray();
    _jsp_string3 = "/student.do?method=del&id=\" + id,\r\n	dataType: \"json\",\r\n	success : function(data) {\r\n		if(data.del == \"true\"){\r\n			alert(\"\u5220\u9664\u6210\u529f\uff01\");\r\n			$(\"#\" + id).remove();\r\n		}\r\n		else{\r\n			alert(\"\u5220\u9664\u5931\u8d25\uff01\");\r\n		}\r\n	},\r\n	error :function(){\r\n		alert(\"\u7f51\u7edc\u8fde\u63a5\u51fa\u9519\uff01\");\r\n	}\r\n});\r\n}\r\n</script>\r\n</head>\r\n<body>\r\n\r\n<input id=\"add\" type=\"button\" onclick=\"add()\" value=\"\u6dfb\u52a0\"/>\r\n<table >\r\n	<tr>\r\n		<td>\u5e8f\u53f7</td>\r\n		<td>\u59d3\u540d</td>\r\n		<td>\u5bc6\u7801</td>\r\n		<td>\u64cd\u4f5c</td>\r\n	</tr>\r\n	".toCharArray();
    _jsp_string9 = "\r\n	\r\n</table>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<title>\u6dfb\u52a0</title>\r\n<script language=\"javascript\" src=\"".toCharArray();
    _jsp_string2 = "/student.do?method=add\";\r\n}\r\n\r\nfunction del(id){\r\n$.ajax( {\r\n	type : \"POST\",\r\n	url : \"".toCharArray();
    _jsp_string5 = "\">\r\n		<td>".toCharArray();
    _jsp_string7 = "</td>\r\n		<td>\r\n			<input type=\"button\" value=\"\u7f16\u8f91\"/> &nbsp;&nbsp;&nbsp;&nbsp;\r\n			<input type=\"button\" onclick=\"del('".toCharArray();
    _jsp_string6 = "</td>\r\n		<td>".toCharArray();
    _jsp_string1 = "/script/jquery.min.js\"></script>\r\n<style>\r\ntable{  border-collapse:collapse;  }\r\ntd{  border:1px solid #f00;  }\r\n</style>\r\n<script type=\"text/javascript\">\r\nfunction add(){\r\n	window.location.href=\"".toCharArray();
    _jsp_string8 = "')\" value=\"\u5220\u9664\"/>\r\n		</td>\r\n	</tr>\r\n	".toCharArray();
  }
}
